# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '<%=project.name%>' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React-native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTAnimation',
    'RCTNetwork',
    'RCTActionSheet',
    'CxxBridge',
    'RCTBlob',
    'RCTWebSocket',
    'RCTImage',
    'DevSupport',
    'RCTVibration',
    'RCTGeolocation',
    'RCTSettings',
    'RCTPushNotification',
    'RCTLinkingIOS'
  ]

<%-block('imports')%>

end
