# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '<%=props.projectName%>' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React-native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'tvOS', # 解决编译时的 fatal error: 'RCTTVRemoteHandler.h' file not found
    'RCTText',
    'RCTAnimation',
    'RCTNetwork',
    'RCTActionSheet',
    'CxxBridge',
    'RCTBlob',
    'RCTWebSocket',
    'RCTImage',
    'DevSupport',
    'RCTVibration',
    'RCTGeolocation',
    'RCTSettings',
    'RCTPushNotification',
    'RCTLinkingIOS'
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # 解决 https://github.com/facebook/react-native/issues/17274 问题
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'yoga'
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
            end
        end
    end
  end

end
